services:
    mysql:
        environment:
            POSTGRES_ROOT_PASSWORD: 12345
        image: postgres
        ports: '[5432:5432]'
        volumes: '[~/apps/mysql:/var/lib/mysql]'
    postgres:
        environment:
            POSTGRES_DATABASE: '[personal_data_base]'
version: 3.7
