server:
    port: ${PORT:8080}
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 10
        password: ${JDBC_DATABASE_PASSWORD:}
        url: ${JDBC_DATABASE_URL:}
        username: ${JDBC_DATABASE_USERNAME:}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
#        defer-datasource-initialization: true
        generate-ddl: false
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true

    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 5MB
    flyway:
        enabled: true
        validate-on-migrate: true